version: '3.1'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp-mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8091:9000'
    restart: always
    volumes:
      - './wp:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wp-mysql
    networks:
      - wpsite
  #nginx
  nginx:
    image: nginx:alpine
    ports:
        - '4080:80'
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
        - ./wp:/var/www/html
    restart: unless-stopped
    links:
      - wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db: